title: Grant Cohoe
author: cohoe
email: grant@grantcohoe.com
description: >
  Random tidbits and other nuggets of knowledge to share.
twitter_username: grantcohoe
github_username:  cohoe
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
minima:
  skin: dark
