title: Grant Cohoe
author:
  name: "Grant Cohoe"
  email: "grant@grantcohoe.com"
tagline: >
  Random tidbits and other nuggets of knowledge.
twitter_username: grantcohoe
github_username:  cohoe
show_excerpts: false
remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a
minima:
  skin: dark
  social_links:
    twitter: grantcohoe
    github: cohoe
    facebook: grantcohoe
    instagram: grantcohoe
    linkedin: grantcohoe
paginate: 5
header_pages:
  - about.md
external_links:
  - title: Home
    url: 'https://www.grantcohoe.com'
  - title: Resume
    url: 'https://resume.grantcohoe.com'
