title: Grant Cohoe
author: cohoe
email: grant@grantcohoe.com
description: >
  Random tidbits and other nuggets of knowledge to share.
twitter_username: grantcohoe
github_username:  cohoe
show_excerpts: true # set to false to remove excerpts on the homepage
#theme: minima
#remote_theme: jekyll/minima
remote_theme: barryclark/jekyll-now
minima:
  skin: dark
  social_links:
    twitter: grantcohoe
    github: cohoe
    facebook: grantcohoe
    instagram: grantcohoe
header_pages:
  - about.md
